name: YunaGUI
version: '${version}'
main: kr.yuna.Main
api-version: '1.20'
description: '능력자매치 섭 GUI'
load: STARTUP
default-permission: not op
author: 'Yn4a'
permissions:
  yuna.admin.commands:
    description: 관리자 전용 명령어들
    default: op
  yuna.users.commands:
   description: 일반 유저 명령어들
   default: not op


commands:
  menu:
    description: 메뉴 여는 임시 명령어
    aliases:
      - 메뉴
  gmc:
    description: 편하게 크리에이티브 모드로 전환 합니다
  gms:
    description: 편하게 서바이벌 모드로 전환합니다
  gma:
    description: 편하게 어드벤쳐(모험)모드로 전환합니다
  gmsp:
    description: 편하게 관전모드로 전환합니다
  아침:
    description: 빠르게 낮으로 바꿉니다
    aliases:
      - day
  스폰:
    description: 스폰으로 이동 해요
    aliases:
      - 넴주
  셋스폰:
    description: 서버의 스폰을 설정하는 명령어에요(관리자 전용)
 
  파티:
    description: 파티 명령어입니다
    aliases:
      - p
  리롯:
    description: 파일 리로드 명령어



